name: microservice-demo
on:
  push:
    branches:
      - master

jobs:
  Build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Deploy to k8s
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh-private-key
          chmod 0600 ssh-private-key
          SSH_HOST=${{ secrets.SSH_HOST }}
          SSH_PARAMS="-i ssh-private-key -o StrictHostKeyChecking=no"
          SSH="ssh $SSH_PARAMS ubuntu@$SSH_HOST"

          #copy deployment yaml to ssh server
          scp $SSH_PARAMS deploy/kubernetes/complete-demo.yaml ubuntu@${SSH_HOST}:~/deploy/complete-demo.yaml

          #kubectl apply 
          $SSH kubectl apply -f deploy/complete-demo.yaml

  